### ISSUE TITLE
how to deal with the updated connector? 

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/DDP_backend#100]
For Sneha, we're using a custom connector which was updated by us. So basically there was a schema change in the API and we had to write and update the connector again. But the updated connector is not pushed to master so the Commcare which is currently there in the platform will not work and we don't want to use that. 

Proposed solution - 

We can build the new connector by building the docker container for that with the latest code but then you'll have to pull the new connector in your connector list and use that one to create the connection. 

But again when the PR is pushed to master how we will update the existing connector?  Something to think about

**Comment by fatchat** [comment]
If I understand correctly:

- The platform is running one version of the Commcare connector
- There is now a new version of a connector available
- The new version is not in the branch of Airbyte which the platform uses

Since we will continue to build new connectors for the immediate future, we need to be able to do this independently of Airbyte 

We should run a "stable Airbyte" + "whatever connectors we want to"

If I understand correctly, we can build "whatever connectors we want to" as docker containers and _somehow_ include them in the "stable Airbyte"

1. Is that correct
2. Do you know how to do this @siddhant3030

**Comment by siddhant3030** [comment]
1. Yes 
2. Yes I know. I can show it to Abhishek tomorrow.

**Comment by siddhant3030** [comment]
And we need to do this for SHRI also. We will build the Kobo Connector on our server.

**Comment by fatchat** [comment]
oh great... phew. let's do this today and make sure everything still works?

**Comment by siddhant3030** [comment]
Cool.

**Comment by fatchat** [comment]
can we document the steps also, say in our g-drive and link to it from here @siddhant3030

**Comment by Abhishek-N** [comment]
@fatchat We did onboard `kobotoolbox`, `surveycto` and `commcare` to the platform and tested it. Created source, destination and connection. 
Sync is yet to be finished from webapp. 
Will add the steps in docs and share the link asap

**Comment by Abhishek-N** [comment]
https://docs.google.com/document/d/1vg87Ge0yB3Y1xDrMt3rCfy69fxI4w8OC4z3RxRqUpZs/edit?usp=share_link

**Comment by fatchat** [comment]
So can we close this issue now? The linked Google document contains the answer to the question and further enhancements will be done directly on the document
@Abhishek-N @siddhant3030 i shall close it, please re-open if you need to
