### ISSUE TITLE
Pull incremental data for an user

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/DDP_backend#282]
We need a way to see the everyday data we're pulling so that we can know that syncs are working properly. For an user there is no way to know that right now.

**Comment by fatchat** [comment]
one way to do this is to look at the `_airbyte_emitted_at` column in each table of the `staging` schema, and filter for the day you want. it's a bit tedious to do this in superset because there might be a lot of `staging` tables, but it's easy to do in a script by iterating through `information_schema.tables where table_schema = 'staging'` ... we could perhaps dump the output into a dalgo table 

this is also part of what @nairabhishek73 and i call "internal analytics"

**Comment by fatchat** [comment]
@fatchat why isn't the superset "daily ingest" dataset updating automatically

**Comment by fatchat** [comment]
the cron job was failing... needed to specify the full path to a config file

@siddhant3030 shall we close this? when we have tooling in future we will get better visibility, i don't think we should build anything more ourselves

**Comment by siddhant3030** [comment]
@fatchat, let's plan this. Happy to sit and discuss.
